module.exports = {
  content: ["./**/*.{html,js}"],
  safelist: [
    'fixed',
    'top-0',
    'left-0',
    'w-64',
    'h-full',
    'bg-white',
    'dark:bg-gray-900',
    'shadow-lg',
    'transform',
    '-translate-x-full',
    'transition-transform',
    'duration-300',
    'ease-in-out',
    'z-[60]',
    'overflow-y-auto',
    'flex',
    'justify-between',
    'items-center',
    'p-4',
    'border-b',
    'dark:border-gray-700',
    'text-lg',
    'font-bold',
    'space-y-4',
    'text-gray-700',
    'dark:text-gray-300',
    'font-semibold',
    'pl-4',
    'mt-2',
    'space-y-2',
    'block',
    'hover:text-gray-900'
  ]
} 